# Generated by Django 5.0 on 2023-12-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='count',
            field=models.IntegerField(verbose_name='终端数量'),
        ),
        migrations.AlterField(
            model_name='city',
            name='img',
            field=models.FileField(max_length=128, upload_to='city/', verbose_name='监测站图片展示'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=32, verbose_name='监测站名称'),
        ),

        migrations.AlterField(
            model_name='city',
            name='weidu',
            field=models.IntegerField(verbose_name='纬度'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='jingdu',
            field=models.IntegerField(verbose_name='经度'),
        ),
    ]
