# Generated by Django 5.0 on 2023-12-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_alter_city_jingdu_alter_city_weidu'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='linkpath',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='联系人信息'),
        ),
        migrations.AddField(
            model_name='city',
            name='linkphone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='联系人手机'),
        ),
        migrations.AddField(
            model_name='city',
            name='linkuser',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='联系人'),
        ),
    ]
