# Generated by Django 5.0 on 2023-12-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_city_linkpath_city_linkphone_city_linkuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='来源监测站')),
                ('wendu', models.FloatField(verbose_name='温度')),
                ('fensu', models.FloatField(verbose_name='风速')),
                ('shidu', models.FloatField(verbose_name='湿度')),
                ('pm25', models.FloatField(verbose_name='PM2.5')),
                ('create_time', models.DateField(verbose_name='创建时间')),
                ('nameid', models.CharField(max_length=32, verbose_name='来源监测站id')),
            ],
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='监测站名称'),
        ),
    ]
