# Generated by Django 5.0 on 2023-12-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_catch_alter_city_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catch',
            name='nameid',
        ),
        migrations.AlterField(
            model_name='catch',
            name='create_time',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
