# Generated by Django 5.0 on 2023-12-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_remove_catch_nameid_alter_catch_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catch',
            name='create_time',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
    ]
