# Generated by Django 5.0 on 2023-12-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_alter_catch_create_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catch',
            old_name='fensu',
            new_name='fengsu',
        ),
    ]
