# Generated by Django 5.0 on 2023-12-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_rename_fensu_catch_fengsu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='title',
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(default=2, max_length=32, verbose_name='名称'),
            preserve_default=False,
        ),
    ]
