# Generated by Django 5.0 on 2023-12-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_alter_department_name_alter_userinfo_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别'),
        ),
    ]
