# Generated by Django 5.0 on 2023-12-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_alter_userinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=128, verbose_name='密码'),
        ),
    ]
