# Generated by Django 5.0 on 2024-06-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0027_alter_user_email_alter_user_phone_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(blank=True, choices=[(1, '普通用户'), (2, '管理员'), (3, 'ROOT')], default=1, null=True, verbose_name='角色'),
        ),
    ]
