# Generated by Django 5.0 on 2024-06-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0028_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.FileField(default='book/default.jpg', max_length=128, upload_to='book/', verbose_name='图书图片展示'),
        ),
    ]
