# Generated by Django 5.0 on 2024-06-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0029_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '借阅中'), (2, '已归还'), (3, '逾期')], default=1, verbose_name='状态'),
        ),
    ]
